/**
 * Every icon the status model can hand a badge, resolved to its lucide
 * component. The model (`shared/status-model.js`) owns the NAMES and stays
 * dependency-free; this file is the one place a name becomes a component, and
 * `family.test.tsx` holds it total against `STATUS_ICON_NAMES`.
 *
 * `NOTE_ICONS` lives apart, in `./note-icons`: `StatusStack` and the toast
 * live in the first-paint barrel and draw only those four, and importing them
 * from HERE would put this whole module in the chunk every visitor downloads
 * first (`scripts/check-dist.mjs`). The map below spreads them in.
 */
import {
  Archive,
  ArchiveX,
  BadgeCheck,
  BadgeMinus,
  BadgeQuestionMark,
  BadgeX,
  Ban,
  BellOff,
  BookOpen,
  Bot,
  Bug,
  CheckCheck,
  Circle,
  CircleAlert,
  CircleArrowRight,
  CircleDashed,
  CircleDot,
  CircleParking,
  CirclePause,
  CirclePlay,
  CircleQuestionMark,
  CircleSlash,
  CircleStop,
  ClipboardCheck,
  Clock,
  CloudOff,
  CloudUpload,
  Construction,
  Download,
  EthernetPort,
  Eye,
  EyeOff,
  FastForward,
  FileCheck,
  FileClock,
  FileMinus,
  FilePenLine,
  FileQuestion,
  FileWarning,
  Flag,
  FolderGit2,
  FolderX,
  GitBranch,
  GitBranchMinus,
  GitCommitHorizontal,
  GitCompare,
  GitMerge,
  GitPullRequestArrow,
  GitPullRequestClosed,
  Hand,
  HeartOff,
  House,
  Hourglass,
  KeyRound,
  Layers,
  LifeBuoy,
  Lightbulb,
  List,
  ListChecks,
  ListMinus,
  ListTodo,
  ListX,
  Lock,
  LogOut,
  MailX,
  MessageCircleCheck,
  MessageCircleQuestion,
  MessageCircleX,
  Minus,
  Moon,
  OctagonAlert,
  OctagonPause,
  OctagonX,
  Pause,
  PlaneLanding,
  Plug,
  PlugZap,
  PowerOff,
  Radio,
  RadioTower,
  RefreshCw,
  Scale,
  Scissors,
  ScrollText,
  SearchCheck,
  Send,
  ShieldCheck,
  ShieldMinus,
  ShieldOff,
  ShieldQuestionMark,
  ShieldX,
  Siren,
  Smartphone,
  Snowflake,
  Square,
  ThermometerSnowflake,
  Timer,
  TimerOff,
  Undo2,
  Unplug,
  UserRound,
  UserRoundCheck,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { UNKNOWN_ICON } from '@shared/status-model.js';
import { NOTE_ICONS } from './note-icons';

export { NOTE_ICONS };

/** Every status icon, by the model's name for it. */
export const STATUS_ICONS: Readonly<Record<string, LucideIcon>> = Object.freeze({
  ...NOTE_ICONS,
  archive: Archive,
  'archive-x': ArchiveX,
  'badge-check': BadgeCheck,
  'badge-minus': BadgeMinus,
  'badge-question-mark': BadgeQuestionMark,
  'badge-x': BadgeX,
  ban: Ban,
  'bell-off': BellOff,
  'book-open': BookOpen,
  bot: Bot,
  bug: Bug,
  'check-check': CheckCheck,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-arrow-right': CircleArrowRight,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  'circle-parking': CircleParking,
  'circle-pause': CirclePause,
  'circle-play': CirclePlay,
  'circle-question-mark': CircleQuestionMark,
  'circle-slash': CircleSlash,
  'circle-stop': CircleStop,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  'cloud-off': CloudOff,
  'cloud-upload': CloudUpload,
  construction: Construction,
  download: Download,
  'ethernet-port': EthernetPort,
  eye: Eye,
  'eye-off': EyeOff,
  'fast-forward': FastForward,
  'file-check': FileCheck,
  'file-clock': FileClock,
  'file-minus': FileMinus,
  'file-pen-line': FilePenLine,
  'file-question': FileQuestion,
  'file-warning': FileWarning,
  flag: Flag,
  'folder-git-2': FolderGit2,
  'folder-x': FolderX,
  'git-branch': GitBranch,
  'git-branch-minus': GitBranchMinus,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-compare': GitCompare,
  'git-merge': GitMerge,
  'git-pull-request-arrow': GitPullRequestArrow,
  'git-pull-request-closed': GitPullRequestClosed,
  hand: Hand,
  'heart-off': HeartOff,
  house: House,
  hourglass: Hourglass,
  'key-round': KeyRound,
  layers: Layers,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  list: List,
  'list-checks': ListChecks,
  'list-minus': ListMinus,
  'list-todo': ListTodo,
  'list-x': ListX,
  lock: Lock,
  'log-out': LogOut,
  'mail-x': MailX,
  'message-circle-check': MessageCircleCheck,
  'message-circle-question': MessageCircleQuestion,
  'message-circle-x': MessageCircleX,
  minus: Minus,
  moon: Moon,
  'octagon-alert': OctagonAlert,
  'octagon-pause': OctagonPause,
  'octagon-x': OctagonX,
  pause: Pause,
  'plane-landing': PlaneLanding,
  plug: Plug,
  'plug-zap': PlugZap,
  'power-off': PowerOff,
  radio: Radio,
  'radio-tower': RadioTower,
  'refresh-cw': RefreshCw,
  scale: Scale,
  scissors: Scissors,
  'scroll-text': ScrollText,
  'search-check': SearchCheck,
  send: Send,
  'shield-check': ShieldCheck,
  'shield-minus': ShieldMinus,
  'shield-off': ShieldOff,
  'shield-question-mark': ShieldQuestionMark,
  'shield-x': ShieldX,
  siren: Siren,
  smartphone: Smartphone,
  snowflake: Snowflake,
  square: Square,
  'thermometer-snowflake': ThermometerSnowflake,
  timer: Timer,
  'timer-off': TimerOff,
  'undo-2': Undo2,
  unplug: Unplug,
  'user-round': UserRound,
  'user-round-check': UserRoundCheck,
  wrench: Wrench,
  zap: Zap,
});

/** The component for a model icon name; a name the map lacks draws as Unknown, never as nothing. */
export function statusIcon(name: string): LucideIcon {
  return STATUS_ICONS[name] ?? STATUS_ICONS[UNKNOWN_ICON];
}
