/**
 * Parity for forward notes: `phase-graph.sh --notes N` against `collectNotes()`.
 *
 * Two readers, one answer. The engine is the authority — the boot prompt is
 * built in bash and the console shells out for it — and the twin exists so a
 * drawer can draw the same thing without a subprocess per phase. The moment
 * they disagree, a phase is shown something it was never handed, or handed
 * something it is never shown, which is the one failure this whole feature
 * exists to prevent. So the corpus is handwritten on purpose: a diamond plan,
 * four handoffs, a rulings ledger and a messages ledger, covering every target
 * (`Phase N`, `Next`, `All`), both ledgers, urgency, expiry, the fold, the
 * bound and the trailer.
 *
 * It also pins the BOOT PROMPT's half of the contract: the block appears iff
 * there are notes, carries them verbatim, and says what to do with each.
 */

// Redirects XDG_STATE_HOME/XDG_CONFIG_HOME before anything resolves them.
import './state-sandbox.ts';

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  collectNotes, parseNoteSection, noteReaches, NOTES_MAX, NOTE_TEXT_MAX,
  type Note, type NoteHandoff, type NoteMessage, type NoteRuling,
} from '../server/parse/notes.ts';

const SKILL = fileURLToPath(new URL('../../', import.meta.url));
const ENGINE = join(SKILL, 'scripts', 'phase-graph.sh');
const FIXTURE = join(SKILL, 'tests', 'fixtures', 'plans', 'diamond.md');

/** The diamond: 1 → {2,3} → 4. */
const DEPS: Record<number, number[]> = { 1: [], 2: [1], 3: [1], 4: [2, 3] };

type Corpus = {
  root: string;
  handoffs: NoteHandoff[];
  rulings: NoteRuling[];
  messages: NoteMessage[];
  rulingsFile: string;
  messagesFile: string;
};

function handoff(
  root: string, phase: number, title: string, status: string, completed: string, section: string,
): NoteHandoff {
  const source = `phase-${String(phase).padStart(2, '0')}-${title}`;
  const body = [
    '---',
    'plan: docs/plans/diamond.md',
    `phase: ${phase}`,
    `title: ${title}`,
    `status: ${status}`,
    `completed: ${completed}`,
    '---',
    '',
    `# Phase ${phase} — ${title}`,
    '',
    '## Notes for later phases',
    '',
    section,
    '',
    '## Outstanding / blockers',
    '',
    'none',
    '',
  ].join('\n');
  writeFileSync(join(root, 'docs', 'handoffs', 'diamond', `${source}.md`), body);
  return { phase, source, done: status === 'complete', completed, body };
}

function corpus(): Corpus {
  const root = mkdtempSync(join(tmpdir(), 'pc-notes-'));
  mkdirSync(join(root, 'docs', 'plans'), { recursive: true });
  mkdirSync(join(root, 'docs', 'handoffs', 'diamond'), { recursive: true });
  copyFileSync(FIXTURE, join(root, 'docs', 'plans', 'diamond.md'));

  const handoffs = [
    handoff(root, 1, 'root', 'complete', '2026-01-02', [
      '- **Phase 4:** the merge reads both halves; do not re-derive either.',
      '- **Next:** the fixture is regenerated by the suite; never hand-edit it,',
      '  and the suite is the only writer.',
      '- **All:** bash 3.2 has no associative arrays.',
    ].join('\n')),
    handoff(root, 2, 'left', 'complete', '2026-01-04',
      '- **Phase 4:** the left half owns the parser.'),
    // Not done: nothing it says has been handed over.
    handoff(root, 3, 'right', 'in-progress', '2026-01-05',
      '- **Phase 4:** written by a phase that has not finished.'),
    // Phase 4's own: never handed back to itself.
    handoff(root, 4, 'merge', 'complete', '2026-01-09',
      '- **All:** addressed to everyone, myself included.'),
  ];

  const rulings: NoteRuling[] = [
    { phase: 1, kind: 'deferral', for: '4', id: 'aaaaaaaaaaaa', at: '2026-01-06T10:00:00Z', what: 'left the second decoder for the merge' },
    { phase: 1, kind: 'deferral', for: 'all', id: 'bbbbbbbbbbbb', at: '2026-01-06T11:00:00Z', what: 'nobody re-spells the scope token' },
    { phase: 2, kind: 'deferral', at: '2026-01-06T12:00:00Z', id: 'cccccccccccc', what: 'the defaulted addressee is next' },
    { phase: 1, kind: 'ambiguity', id: 'dddddddddddd', at: '2026-01-06T13:00:00Z', what: 'an ambiguity is addressed to nobody' },
  ];
  const rulingsFile = join(root, 'rulings.ndjson');
  writeFileSync(rulingsFile, rulings.map((r) => JSON.stringify({
    version: 1, type: 'ruling', id: r.id, slug: 'diamond', phase: r.phase, kind: r.kind,
    what: r.what, ...(r.for ? { for: r.for } : {}), at: r.at,
  })).join('\n') + '\n');

  const messages: NoteMessage[] = [
    {
      id: '111111111111', from: 'phase:diamond/2', to: 'phase:diamond/4', deliver: 'boot',
      priority: 'normal', state: 'held', text: 'the branch was re-cut', writtenAt: '2026-01-07T09:00:00Z',
    },
    {
      id: '222222222222', from: 'phase:diamond/1', to: 'all:', deliver: 'boot',
      priority: 'high', state: 'queued', text: 'the token is in .secrets/, never the tree', writtenAt: '2026-01-07T10:00:00Z',
    },
    // Already delivered — the fold says so, so it is not handed over twice.
    {
      id: '333333333333', from: 'phase:diamond/2', to: 'phase:diamond/4', deliver: 'boot',
      priority: 'normal', state: 'delivered', text: 'delivered once already', writtenAt: '2026-01-07T11:00:00Z',
    },
    // Not `boot`: addressed to a session, and phase 4 has none yet.
    {
      id: '444444444444', from: 'phase:diamond/2', to: 'phase:diamond/4', deliver: 'now',
      priority: 'normal', state: 'queued', text: 'answer me this turn', writtenAt: '2026-01-07T12:00:00Z',
    },
    // Expired.
    {
      id: '555555555555', from: 'phase:diamond/2', to: 'phase:diamond/4', deliver: 'boot',
      priority: 'normal', state: 'queued', text: 'this one timed out', writtenAt: '2026-01-07T13:00:00Z',
      expires: '2026-01-08T00:00:00Z',
    },
  ];
  const messagesFile = join(root, 'messages.ndjson');
  const lines = messages.map((m) => JSON.stringify({
    version: 1, type: 'message', id: m.id, slug: 'diamond', phase: Number(m.from.split('/')[1]),
    kind: 'note', from: m.from, to: m.to, deliver: m.deliver, priority: m.priority,
    text: m.text, ...(m.expires ? { expires: m.expires } : {}), written_at: m.writtenAt,
  }));
  // The fold is the ledger's, not the reader's: `333333333333` is delivered
  // because a `delivery` line says so, exactly as the console records it.
  lines.push(JSON.stringify({
    type: 'delivery', id: '333333333333', state: 'delivered', via: 'boot-prompt',
    to: 'phase:diamond/4', at: '2026-01-07T11:30:00Z', by: 'console',
  }));
  writeFileSync(messagesFile, lines.join('\n') + '\n');

  return { root, handoffs, rulings, messages, rulingsFile, messagesFile };
}

function bash(box: Corpus, args: string[], extra: Record<string, string> = {}): string {
  return execFileSync('/bin/bash', [ENGINE, 'diamond', ...args], {
    encoding: 'utf8',
    env: {
      ...process.env,
      DOCS_ROOT: box.root,
      PE_RULINGS_FILE: box.rulingsFile,
      PE_MESSAGES_FILE: box.messagesFile,
      PE_NOW: '2026-02-01T00:00:00Z',
      ...extra,
    },
  });
}

function bashNotes(box: Corpus, phase: number, extra: Record<string, string> = {}): Note[] {
  return bash(box, ['--notes', String(phase)], extra)
    .split('\n')
    .filter((line) => line.trim())
    .map((line) => {
      const [source, kind, id, at, ...rest] = line.split('\t');
      return { source, kind: kind as Note['kind'], id, at, text: rest.join('\t') };
    });
}

function twinNotes(box: Corpus, phase: number, over: Partial<Parameters<typeof collectNotes>[0]> = {}): Note[] {
  return collectNotes({
    phase,
    deps: DEPS[phase],
    handoffs: box.handoffs,
    rulings: box.rulings,
    messages: box.messages,
    now: new Date('2026-02-01T00:00:00Z'),
    ...over,
  });
}

/* ------------------------------------------------------------------ *
 * The two readers agree
 * ------------------------------------------------------------------ */

test('bash and the twin hand every phase of the diamond exactly the same notes', () => {
  const box = corpus();
  for (const phase of [1, 2, 3, 4]) {
    assert.deepEqual(twinNotes(box, phase), bashNotes(box, phase), `phase ${phase}`);
  }
});

test('phase 4 is handed all three sources, urgent first and then oldest to newest', () => {
  const box = corpus();
  const notes = bashNotes(box, 4);
  assert.deepEqual(notes.map((n) => [n.kind, n.text]), [
    // The one `high` message, hoisted above everything older.
    ['message', 'the token is in .secrets/, never the tree'],
    // Then oldest first: phase 1's handoff, phase 2's, the two deferrals for
    // it, and the ordinary boot message.
    ['handoff', 'the merge reads both halves; do not re-derive either.'],
    ['handoff', 'bash 3.2 has no associative arrays.'],
    ['handoff', 'the left half owns the parser.'],
    ['deferral', 'left the second decoder for the merge'],
    ['deferral', 'nobody re-spells the scope token'],
    ['deferral', 'the defaulted addressee is next'],
    ['message', 'the branch was re-cut'],
  ]);
  // The ids carry through, so a session can acknowledge the mail it acted on.
  assert.equal(notes.find((n) => n.text === 'the branch was re-cut')?.id, '111111111111');
  assert.equal(notes.find((n) => n.kind === 'handoff')?.id, '-');
});

test('`Next` follows the dependency edge, in both readers', () => {
  const box = corpus();
  // 2 and 3 depend on 1, so both are handed the root's `Next` note — with the
  // continuation line folded in. 4 does not depend on 1 and is handed none.
  for (const phase of [2, 3]) {
    const texts = bashNotes(box, phase).map((n) => n.text);
    assert.ok(texts.includes('the fixture is regenerated by the suite; never hand-edit it, and the suite is the only writer.'));
    assert.deepEqual(twinNotes(box, phase).map((n) => n.text), texts);
  }
  assert.ok(!bashNotes(box, 4).some((n) => n.text.startsWith('the fixture is regenerated')));
});

test('what neither reader hands on: an unfinished handoff, your own words, settled or expired mail', () => {
  const box = corpus();
  const everything = [1, 2, 3, 4].flatMap((p) => bashNotes(box, p)).map((n) => n.text);
  for (const never of [
    'written by a phase that has not finished.',
    'delivered once already',
    'answer me this turn',
    'this one timed out',
    'an ambiguity is addressed to nobody',
  ]) {
    assert.ok(!everything.includes(never), never);
  }
  // Phase 4's own `All` bullet reaches every OTHER phase — it is a broadcast,
  // and a broadcast that skipped its author is still a broadcast. What it must
  // never do is come back to phase 4 as advice from a predecessor.
  assert.ok(!bashNotes(box, 4).some((n) => n.text === 'addressed to everyone, myself included.'));
  assert.ok(bashNotes(box, 2).some((n) => n.text === 'addressed to everyone, myself included.'));
});

test('`Messaging: off` suppresses the mail source in both readers, and nothing else', () => {
  const box = corpus();
  const plan = join(box.root, 'docs', 'plans', 'diamond.md');
  writeFileSync(plan, `${readFileSync(plan, 'utf8')}\n## Session budget\n\n> **Messaging:** off\n`);
  const fromBash = bashNotes(box, 4);
  assert.deepEqual(twinNotes(box, 4, { messaging: 'off' }), fromBash);
  assert.ok(!fromBash.some((n) => n.kind === 'message'));
  assert.ok(fromBash.some((n) => n.kind === 'deferral'), 'a deferral is not messaging');
  assert.ok(fromBash.some((n) => n.kind === 'handoff'), 'a handoff note is not messaging');
});

test('the bound keeps the newest and both readers append the same trailer', () => {
  const box = corpus();
  const many = Array.from({ length: 20 }, (_, i) => `- **Phase 4:** note number ${i + 1}`).join('\n');
  box.handoffs = [handoff(box.root, 1, 'root', 'complete', '2026-01-02', many), ...box.handoffs.slice(1)];
  box.rulings = [];
  box.messages = [];
  writeFileSync(box.rulingsFile, '');
  writeFileSync(box.messagesFile, '');

  const fromBash = bashNotes(box, 4);
  assert.deepEqual(twinNotes(box, 4), fromBash);
  assert.equal(fromBash.length, NOTES_MAX + 1, 'twelve notes and one trailer');
  assert.equal(fromBash.at(-1)!.kind, 'trailer');
  // 21 candidates — phase 1's twenty and phase 2's one — so nine are dropped.
  assert.match(fromBash.at(-1)!.text, /9 older notes/);
  // Phase 1's bullets share one `completed:` date, so `seq` is the tiebreak
  // and the LAST written survive; phase 2's is newer than all of them and is
  // last in display order.
  assert.equal(fromBash[0].text, 'note number 10');
  assert.equal(fromBash[10].text, 'note number 20');
  assert.equal(fromBash[NOTES_MAX - 1].text, 'the left half owns the parser.');
});

test('a note is clipped to the same length by both readers', () => {
  const box = corpus();
  box.handoffs = [handoff(box.root, 1, 'root', 'complete', '2026-01-02', `- **Phase 4:** ${'x'.repeat(600)}`), ...box.handoffs.slice(1)];
  box.rulings = [];
  box.messages = [];
  writeFileSync(box.rulingsFile, '');
  writeFileSync(box.messagesFile, '');
  const fromBash = bashNotes(box, 4);
  assert.equal(fromBash[0].text.length, NOTE_TEXT_MAX);
  assert.deepEqual(twinNotes(box, 4), fromBash);
});

/* ------------------------------------------------------------------ *
 * The boot prompt's half
 * ------------------------------------------------------------------ */

test('a prompt with nothing left for it is byte-identical to what it always was', () => {
  const box = corpus();
  // Empty both ledgers and address phase 4's broadcast to itself, so nothing
  // anywhere is left for phase 1 — the root of the diamond, which nobody
  // preceded. Its prompt must not gain so much as a blank line.
  writeFileSync(box.rulingsFile, '');
  writeFileSync(box.messagesFile, '');
  handoff(box.root, 4, 'merge', 'complete', '2026-01-09', '- **Phase 4:** addressed to myself.');
  assert.deepEqual(bashNotes(box, 1), []);
  assert.ok(!bash(box, ['--boot-prompt', '1']).includes('Notes from earlier phases'));
});

test('the boot prompt carries the block, and says what to do with each note', () => {
  const box = corpus();
  const merge = bash(box, ['--boot-prompt', '4']);
  assert.match(merge, /### Notes from earlier phases \(8\)/);
  for (const note of bashNotes(box, 4)) assert.ok(merge.includes(note.text), note.text);
  // The closing instruction — what a session owes each note, and the command
  // that tells a sender its mail landed.
  assert.match(merge, /what became of each/);
  assert.match(merge, /phase-msg\.sh diamond 4 ack <id>/);
  // The block sits after the board and before the decisions manifest: it is
  // the one part of the prompt nobody could have written into the plan.
  assert.ok(merge.indexOf('for live state.') < merge.indexOf('### Notes from earlier phases'));
  assert.ok(merge.indexOf('### Notes from earlier phases') < merge.indexOf('DECISIONS'));
});

test('a prompt whose notes are all handoff bullets offers no ack line', () => {
  const box = corpus();
  writeFileSync(box.rulingsFile, '');
  writeFileSync(box.messagesFile, '');
  const prompt = bash(box, ['--boot-prompt', '4']);
  assert.match(prompt, /### Notes from earlier phases/);
  assert.ok(!prompt.includes('phase-msg.sh diamond 4 ack'));
});

/* ------------------------------------------------------------------ *
 * The twin's own edges
 * ------------------------------------------------------------------ */

test('the section parser reads every spelling of an address and refuses the rest', () => {
  const rows = parseNoteSection([
    '## Notes for later phases',
    '',
    '- **Phase 7:** bold and addressed',
    '- **For phase 8:** the other spelling',
    '* Phase 9: no emphasis at all',
    '- **NEXT:** case does not matter',
    '- **All:** everybody',
    '- **Outstanding:** a label that is not an address',
    '- no colon at all',
    '',
    '## Outstanding / blockers',
    '- **Phase 7:** outside the section entirely',
  ].join('\n'));
  assert.deepEqual(rows, [
    { target: '7', text: 'bold and addressed' },
    { target: '8', text: 'the other spelling' },
    { target: '9', text: 'no emphasis at all' },
    { target: 'next', text: 'case does not matter' },
    { target: 'all', text: 'everybody' },
  ]);
});

test('noteReaches never hands a phase its own note, whatever the address', () => {
  for (const target of ['4', 'next', 'all']) {
    assert.equal(noteReaches(target, 4, 4, [2, 3]), false, target);
  }
  assert.equal(noteReaches('next', 2, 4, [2, 3]), true);
  assert.equal(noteReaches('next', 1, 4, [2, 3]), false, 'next is a dependency edge, not a phase number');
  assert.equal(noteReaches('all', 1, 4, [2, 3]), true);
});
