#!/usr/bin/env bats
#
# Forward notes — what a phase is handed by the phases before it.
#
# `--notes N` is the reader, and it has three sources that are three different
# ARTEFACTS with three different lifetimes: a handoff section a person wrote
# and a person reads, a deferral ruling a session recorded on its way past
# something, and a boot-deliverable message a peer addressed to a phase that
# had not started. They are one command because the QUESTION is one — "what
# was left for me?" — and a session that has to ask three is a session that
# asks none.
#
# Source 1 landed in phase 2 (handoff bullets addressed `- **Phase N:** …`);
# this suite is phase 11's, which adds `Next`/`All`, continuation lines, the
# two ledgers, the ordering, the bound, and the boot-prompt block.

load ../helpers/test_helper

setup() { setup_docs diamond diamond; }

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

# A handoff with a `## Notes for later phases` section. The body arrives on
# stdin so a test reads as the markdown it is writing.
# usage: notes_handoff <N> <title> <status> [completed-date]  <<'EOF' … EOF
notes_handoff() {
  local n="$1" title="$2" status="$3" completed="${4:-}" pad f
  pad="$(printf '%02d' "$n")"
  f="$DOCS_ROOT/docs/handoffs/diamond/phase-$pad-$title.md"
  mkdir -p "$(dirname "$f")"
  {
    printf -- '---\n'
    printf 'plan: docs/plans/diamond.md\n'
    printf 'phase: %s\n' "$n"
    printf 'title: %s\n' "$title"
    printf 'status: %s\n' "$status"
    [ -n "$completed" ] && printf 'completed: %s\n' "$completed"
    printf -- '---\n\n'
    printf '# Phase %s — %s\n\n' "$n" "$title"
    printf '## Notes for later phases\n\n'
    cat
    printf '\n## Outstanding / blockers\n\nnone\n'
  } > "$f"
}

# The two ledgers live where phase-outcome.sh and phase-msg.sh put them, and
# both honour an injected path — which is exactly how a lane and a test reach
# them without a console.
use_ledgers() {
  export PE_RULINGS_FILE="$BATS_TEST_TMPDIR/rulings.ndjson"
  export PE_MESSAGES_FILE="$BATS_TEST_TMPDIR/messages.ndjson"
  : > "$PE_RULINGS_FILE"
  : > "$PE_MESSAGES_FILE"
}

# usage: a_deferral <writer-phase> <for> <at> <text>
a_deferral() {
  printf '{"version":1,"type":"ruling","id":"%s","slug":"diamond","phase":%s,"kind":"deferral","what":"%s","for":"%s","at":"%s"}\n' \
    "$(printf '%s' "$4$3" | cksum | tr -d ' ' | cut -c1-12)" "$1" "$4" "$2" "$3" >> "$PE_RULINGS_FILE"
}

# usage: a_message <id> <from-phase> <to> <deliver> <priority> <written_at> <text> [expires]
a_message() {
  local expires=""
  [ -n "${8:-}" ] && expires=",\"expires\":\"$8\""
  printf '{"version":1,"type":"message","id":"%s","slug":"diamond","phase":%s,"kind":"note","from":"phase:diamond/%s","to":"%s","deliver":"%s","priority":"%s","text":"%s"%s,"written_at":"%s"}\n' \
    "$1" "$2" "$2" "$3" "$4" "$5" "$7" "$expires" "$6" >> "$PE_MESSAGES_FILE"
}

# The note text of every row `--notes` printed, one per line (column 5).
note_texts() { awk -F'\t' '{print $5}'; }

# ---------------------------------------------------------------------------
# The grammar: Phase N · Next · All · continuation
# ---------------------------------------------------------------------------

@test "--notes: an addressed bullet reaches the phase it names, and nobody else" {
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 4:** the merge reads both halves; do not re-derive either.
- **Phase 2:** the left half owns the parser.
EOF
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "the merge reads both halves"
  refute_contains "$output" "the left half owns the parser"

  run pg diamond --notes 2
  assert_contains "$output" "the left half owns the parser"
  refute_contains "$output" "the merge reads both halves"
}

@test "--notes: \`Next\` reaches the phases that DEPEND on the writer, and only those" {
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Next:** the fixture is regenerated by the suite; never hand-edit it.
EOF
  # 2 and 3 both depend on 1.
  run pg diamond --notes 2
  assert_contains "$output" "never hand-edit it"
  run pg diamond --notes 3
  assert_contains "$output" "never hand-edit it"
  # 4 depends on 2 and 3, NOT on 1 — "next" is a dependency relation, not a
  # phase number, or every note a root wrote would reach the whole plan.
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  refute_contains "$output" "never hand-edit it"
}

@test "--notes: \`All\` reaches every phase but the writer's own" {
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **All:** bash 3.2 has no associative arrays; the engine targets it.
EOF
  for p in 2 3 4; do
    run pg diamond --notes "$p"
    assert_contains "$output" "no associative arrays"
  done
  # Its own phase is not handed its own note — it wrote it.
  run pg diamond --notes 1
  [ "$status" -eq 0 ]
  refute_contains "$output" "no associative arrays"
}

@test "--notes: a continuation line joins the bullet it follows" {
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 4:** the ledger's column order is fixed;
  read it by header name, never by index.
- **Phase 4:** and this one is separate.
EOF
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "column order is fixed; read it by header name, never by index."
  assert_contains "$output" "and this one is separate."
  # Two notes, not three: the continuation is part of the first, not a row of
  # its own — a wrapped sentence must not read as a second instruction.
  [ "$(printf '%s\n' "$output" | grep -c 'handoff')" -eq 2 ]
}

@test "--notes: the scaffolded section's own example is a COMMENT, not a note" {
  # The scaffold teaches the grammar by showing `- **Phase 7:** …` inside an
  # HTML comment. Read as content it hands phase 7 an example nobody wrote —
  # and, since 7 is not in this plan, fails the plan's own F26 the moment a
  # handoff is created. Every freshly scaffolded handoff, on every plan.
  pe_newho diamond 1 root complete >/dev/null
  run pg diamond --notes 2
  [ "$status" -eq 0 ]
  [ -z "$output" ]
  run pe_validate diamond
  [ "$status" -eq 0 ]
  assert_contains "$output" "VALIDATE OK"
}

@test "--notes: a note is bounded at 500 characters" {
  local long
  long="$(awk 'BEGIN { while (i++ < 600) printf "x" }')"
  notes_handoff 1 root complete 2026-01-02 <<EOF
- **Phase 4:** $long
EOF
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  [ "$(printf '%s' "$output" | awk -F'\t' '{print length($5)}')" -eq 500 ]
}

# ---------------------------------------------------------------------------
# Which handoffs are read: done only, never your own
# ---------------------------------------------------------------------------

@test "--notes: only a DONE phase's handoff is read" {
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 4:** from a phase that finished.
EOF
  notes_handoff 2 left in-progress 2026-01-03 <<'EOF'
- **Phase 4:** from a phase still running.
EOF
  notes_handoff 3 right blocked 2026-01-03 <<'EOF'
- **Phase 4:** from a phase that is stuck.
EOF
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "from a phase that finished."
  # A phase still working may yet change its mind; a blocked one has not
  # finished the thought. Neither has handed anything over.
  refute_contains "$output" "still running"
  refute_contains "$output" "that is stuck"
}

@test "--notes: a phase is never handed its own handoff's notes" {
  notes_handoff 4 merge complete 2026-01-05 <<'EOF'
- **Phase 4:** addressed to myself.
- **All:** addressed to everyone, myself included.
EOF
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  refute_contains "$output" "addressed to myself"
  refute_contains "$output" "myself included"
}

# ---------------------------------------------------------------------------
# Order, bound, trailer
# ---------------------------------------------------------------------------

@test "--notes: notes arrive oldest first" {
  notes_handoff 2 left complete 2026-01-04 <<'EOF'
- **Phase 4:** written second.
EOF
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 4:** written first.
EOF
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  local texts; texts="$(printf '%s\n' "$output" | note_texts)"
  [ "$(printf '%s\n' "$texts" | head -1)" = "written first." ]
  [ "$(printf '%s\n' "$texts" | sed -n 2p)" = "written second." ]
}

@test "--notes: an urgent message is hoisted above everything older" {
  use_ledgers
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 4:** an ordinary note.
EOF
  a_message aaaaaaaaaaaa 2 "phase:diamond/4" boot high 2026-02-01T00:00:00Z "the branch was re-cut; pull before you build."
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  [ "$(printf '%s\n' "$output" | note_texts | head -1)" = "the branch was re-cut; pull before you build." ]
}

@test "--notes: the list is bounded, and says how many it dropped" {
  local i
  {
    printf -- '---\nplan: docs/plans/diamond.md\nphase: 1\ntitle: root\nstatus: complete\ncompleted: 2026-01-02\n---\n\n'
    printf '## Notes for later phases\n\n'
    for i in $(seq 1 20); do printf -- '- **Phase 4:** note number %s\n' "$i"; done
  } > "$DOCS_ROOT/docs/handoffs/diamond/phase-01-root.md"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  # 12 notes plus one trailer row.
  [ "$(printf '%s\n' "$output" | grep -c .)" -eq 13 ]
  assert_contains "$output" "8 older notes"
  # The NEWEST twelve are the ones kept — an old note that still mattered has
  # been read by now, and the trailer says so rather than pretending.
  assert_contains "$output" "note number 20"
  refute_contains "$output" "note number 8	"
}

# ---------------------------------------------------------------------------
# Source 2: deferral rulings
# ---------------------------------------------------------------------------

@test "--notes: a deferral ruling addressed to this phase is a note" {
  use_ledgers
  a_deferral 1 4 2026-01-03T10:00:00Z "left the second decoder for the merge phase"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "left the second decoder for the merge phase"
  assert_contains "$output" "deferral"
  # And nobody else's.
  run pg diamond --notes 2
  refute_contains "$output" "second decoder"
}

@test "--notes: a deferral for \`next\` follows the dependency edge; \`all\` reaches everyone" {
  use_ledgers
  a_deferral 1 next 2026-01-03T10:00:00Z "the root left the harder half"
  a_deferral 1 all  2026-01-03T11:00:00Z "nobody re-spells the scope token"
  run pg diamond --notes 2
  assert_contains "$output" "the root left the harder half"
  assert_contains "$output" "nobody re-spells the scope token"
  run pg diamond --notes 4
  refute_contains "$output" "the root left the harder half"
  assert_contains "$output" "nobody re-spells the scope token"
}

@test "--notes: only DEFERRAL rulings are notes — an ambiguity is not addressed to anyone" {
  use_ledgers
  printf '{"version":1,"type":"ruling","id":"bbbbbbbbbbbb","slug":"diamond","phase":1,"kind":"ambiguity","what":"read the flag as inclusive","at":"2026-01-03T10:00:00Z"}\n' >> "$PE_RULINGS_FILE"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  refute_contains "$output" "read the flag as inclusive"
}

@test "--notes: an absent ledger is nothing at all, not an error" {
  export PE_RULINGS_FILE="$BATS_TEST_TMPDIR/nope/rulings.ndjson"
  export PE_MESSAGES_FILE="$BATS_TEST_TMPDIR/nope/messages.ndjson"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# ---------------------------------------------------------------------------
# Source 3: boot-deliverable messages
# ---------------------------------------------------------------------------

@test "--notes: a boot-deliverable message addressed to this phase is a note" {
  use_ledgers
  a_message aaaaaaaaaaaa 2 "phase:diamond/4" boot normal 2026-02-01T00:00:00Z "the fixture moved to tests/fixtures/plans/"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "the fixture moved"
  assert_contains "$output" "aaaaaaaaaaaa"
  assert_contains "$output" "message"
}

@test "--notes: only \`boot\` mail waits for a phase — \`now\` and \`next-turn\` are for a live session" {
  use_ledgers
  a_message aaaaaaaaaaaa 2 "phase:diamond/4" now       normal 2026-02-01T00:00:00Z "answer me this turn"
  a_message bbbbbbbbbbbb 2 "phase:diamond/4" next-turn normal 2026-02-01T00:00:00Z "answer me next turn"
  a_message cccccccccccc 2 "phase:diamond/4" boot      normal 2026-02-01T00:00:00Z "read me when you board"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "read me when you board"
  refute_contains "$output" "answer me this turn"
  refute_contains "$output" "answer me next turn"
}

@test "--notes: an expired message is not handed on" {
  use_ledgers
  a_message aaaaaaaaaaaa 2 "phase:diamond/4" boot normal 2026-02-01T00:00:00Z "this one is still good" "2099-01-01T00:00:00Z"
  a_message bbbbbbbbbbbb 2 "phase:diamond/4" boot normal 2026-02-01T00:00:00Z "this one timed out"    "2026-02-02T00:00:00Z"
  PE_NOW=2026-03-01T00:00:00Z run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "this one is still good"
  refute_contains "$output" "this one timed out"
}

@test "--notes: a message already settled is not handed on again" {
  use_ledgers
  a_message aaaaaaaaaaaa 2 "phase:diamond/4" boot normal 2026-02-01T00:00:00Z "delivered once already"
  a_message bbbbbbbbbbbb 2 "phase:diamond/4" boot normal 2026-02-01T00:00:00Z "still waiting"
  printf '{"type":"delivery","id":"aaaaaaaaaaaa","state":"delivered","via":"boot-prompt","to":"phase:diamond/4","at":"2026-02-02T00:00:00Z","by":"console"}\n' >> "$PE_MESSAGES_FILE"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  assert_contains "$output" "still waiting"
  refute_contains "$output" "delivered once already"
}

@test "--notes: a phase is never handed its own mail" {
  use_ledgers
  a_message aaaaaaaaaaaa 4 "all:" boot normal 2026-02-01T00:00:00Z "broadcast from the merge phase"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  refute_contains "$output" "broadcast from the merge phase"
  run pg diamond --notes 2
  assert_contains "$output" "broadcast from the merge phase"
}

@test "--notes: \`Messaging: off\` suppresses the mail source and nothing else" {
  use_ledgers
  a_message aaaaaaaaaaaa 2 "phase:diamond/4" boot normal 2026-02-01T00:00:00Z "mail nobody will read"
  a_deferral 1 4 2026-01-03T10:00:00Z "a deferral is not messaging"
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 4:** a handoff note is not messaging either.
EOF
  # The plan turns messaging off in its §Session budget.
  printf '\n## Session budget\n\n> **Messaging:** off\n' >> "$DOCS_ROOT/docs/plans/diamond.md"
  run pg diamond --notes 4
  [ "$status" -eq 0 ]
  refute_contains "$output" "mail nobody will read"
  assert_contains "$output" "a deferral is not messaging"
  assert_contains "$output" "a handoff note is not messaging either."
}

# ---------------------------------------------------------------------------
# The boot prompt carries the block — iff there is one
# ---------------------------------------------------------------------------

@test "--boot-prompt: with no notes the prompt is byte-identical to what it was" {
  run pg diamond --boot-prompt 2
  [ "$status" -eq 0 ]
  refute_contains "$output" "Notes from earlier phases"
}

@test "--boot-prompt: the notes block follows the DAG sentence and names what to do with each" {
  use_ledgers
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 2:** the parser is the left half's; do not re-derive it.
EOF
  a_message aaaaaaaaaaaa 3 "phase:diamond/2" boot normal 2026-02-01T00:00:00Z "the branch moved"
  run pg diamond --boot-prompt 2
  [ "$status" -eq 0 ]
  assert_contains "$output" "### Notes from earlier phases"
  assert_contains "$output" "do not re-derive it"
  assert_contains "$output" "the branch moved"
  # The closing instruction: say what became of each, and acknowledge mail.
  assert_contains "$output" "what became of each"
  assert_contains "$output" "phase-msg.sh diamond 2 ack"
  # It sits AFTER the DAG sentence and BEFORE the decisions manifest.
  local dag notes dec
  dag="$(printf '%s\n' "$output" | grep -n 'for live state' | head -1 | cut -d: -f1)"
  notes="$(printf '%s\n' "$output" | grep -n 'Notes from earlier phases' | head -1 | cut -d: -f1)"
  dec="$(printf '%s\n' "$output" | grep -n "DECISIONS" | head -1 | cut -d: -f1)"
  [ "$dag" -lt "$notes" ]
  [ "$notes" -lt "$dec" ]
}

@test "--boot-prompt: the ack line is only offered when there is mail to acknowledge" {
  notes_handoff 1 root complete 2026-01-02 <<'EOF'
- **Phase 2:** a plain handoff note, nothing to acknowledge.
EOF
  run pg diamond --boot-prompt 2
  [ "$status" -eq 0 ]
  assert_contains "$output" "### Notes from earlier phases"
  refute_contains "$output" "phase-msg.sh diamond 2 ack"
  refute_contains "$output" "Acknowledge the ones you act on"
}

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

@test "--notes: a phase that is not in the plan is refused" {
  run pg diamond --notes 9
  [ "$status" -eq 2 ]
  assert_contains "$output" "not in this plan"
}

@test "--notes: with no phase argument it is a usage error" {
  run pg diamond --notes
  [ "$status" -eq 2 ]
}
